const CHANGE_SEARCH_KEY = "CHANGE_SEARCH_KEY";
const FETCH_COCKTAILS_SUCCESS = "FETCH_COCKTAILS_SUCCESS";
const FETCH_COCKTAILS_FAILURE = "FETCH_COCKTAILS_FAILURE";
const OPEN_SIDEBAR = "OPEN_SIDEBAR";
const CLOSE_SIDEBAR = "CLOSE_SIDEBAR"
const SET_LOADING = "SET_LOADING";
const GET_COCKTAIL_SUCCESS = "GET_COCKTAIL_SUCCESS";
const GET_COCKTAIL_FAILURE = "GET_COCKTAIL_FAILURE";
export {
    CHANGE_SEARCH_KEY,
    FETCH_COCKTAILS_FAILURE,
    FETCH_COCKTAILS_SUCCESS,
    OPEN_SIDEBAR,
    CLOSE_SIDEBAR,
    SET_LOADING,
    GET_COCKTAIL_SUCCESS,
    GET_COCKTAIL_FAILURE
};